### ISSUE TITLE
function clone issue happening as of version 1.1.4

### ISSUE THREAD

**Issue by croucha** [kurtmilam/underscoreDeepExtend#17]
Hi there,

I have a function with additional properties defined as:

`
var foo = function(options) {};
foo.bar = function(options) {};
`

For some reason, when deep cloning this like:
`
var options =  {};
options = _.deepExtend(options, {
    foo: foo,
});
`

The function under "foo" doesn't remain intact anymore.  It shows up as only an object now with the additional properties (bar) and not as a function with additional function properties.  This wasn't happening until version 1.1.4.

**Comment by kurtmilam** [comment]
The new behavior is due to a change in how `_.clone` works. That change was introduced in lodash version 3.0, according to my tests.

I ran your scenario with version 1.1.5 of this module and multiple versions of lodash. The output was as you were hoping with all lodash versions prior to 3.0 that I tested. It was as you reported with 3.0 and all lodash versions later than 3.0 that I tested.

Cloning functions was an unintended side effect for me, but I'll give some thought to a solution.

**Comment by kurtmilam** [comment]
I'm strongly inclined to leave this as-is. [lodash v3.0.0](https://github.com/lodash/lodash/wiki/Changelog#v300) was released on January 26, 2015, so this behavior has been standard for almost 18 months for anyone using up-to-date modules. I don't feel comfortable making a potentially breaking change to 18-month-old behavior to reinstate an unintended side effect when this module is a dependency of several external modules.

Here's the lodash v3.0.0 ChangeLog compatibility warning detailing the relevant change and its potential effects:
> Made `_.clone` & `_.cloneDeep` return a new object for unsupported types.

And here's a relevant excerpt from the current documentation for [_.clone](https://lodash.com/docs#clone):
> The own enumerable properties of arguments objects are cloned as plain objects. **An empty object is returned for uncloneable values** such as error objects, **functions**, DOM nodes, and WeakMaps.

I think your best bet would be to use this module with a pre v3 version of lodash if you need to have the desired functionality.
